### ISSUE TITLE
Error: The id "enum.functions." is invalid. Ids are not allowed to end in "."

### ISSUE THREAD

**Issue by Beaststriker** [klein0r/ioBroker.gira-iot#60]
### The problem

Seit dem Firmwareupgrade auf 4.12 kommt nun folgender Fehler:
Error: The id "enum.functions." is invalid. Ids are not allowed to end in "."

Lg Stefan

### Version of nodejs

16.19.1

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

0.1.3

### Operating system running ioBroker

Linux Ubuntu

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
0.3.0 ist die aktuelle Version des Adapters...
